import { ClassSession } from '../types';

export const mockTimetableData: ClassSession[] = [
  {
    id: 1,
    subject: 'Computer Science Fundamentals',
    lecturer: 'Prof. Sarah Johnson',
    classroom: '3201',
    time: '09:30 - 10:50',
    day: 'Monday',
    groups: ['CS-1A', 'CS-1B'],
    duration: '80 min',
    week: 'both',
    teachingGroup: 'IT101'
  },
  {
    id: 2,
    subject: 'Mathematics for Computing',
    lecturer: 'Prof. Michael Chen',
    classroom: '5308',
    time: '11:00 - 12:20',
    day: 'Monday',
    groups: ['CS-1A'],
    duration: '80 min',
    week: 'numerator',
    teachingGroup: 'MT205'
  },
  {
    id: 3,
    subject: 'Database Systems',
    lecturer: 'Prof. Emily Watson',
    classroom: '12405',
    time: '12:50 - 14:10',
    day: 'Monday',
    groups: ['CS-2A', 'CS-2B'],
    duration: '80 min',
    week: 'denominator',
    teachingGroup: 'DB319'
  },
  {
    id: 4,
    subject: 'Web Development',
    lecturer: 'Prof. James Martinez',
    classroom: '7210',
    time: '09:30 - 10:50',
    day: 'Tuesday',
    groups: ['CS-2A'],
    duration: '80 min',
    week: 'numerator',
    teachingGroup: 'WD217'
  },
  {
    id: 5,
    subject: 'Software Engineering',
    lecturer: 'Prof. Linda Brown',
    classroom: '1503',
    time: '12:50 - 14:10',
    day: 'Tuesday',
    groups: ['CS-3A', 'CS-3B'],
    duration: '80 min',
    week: 'both',
    teachingGroup: 'SE401'
  },
  {
    id: 6,
    subject: 'Data Structures & Algorithms',
    lecturer: 'Prof. Robert Lee',
    classroom: '8107',
    time: '11:00 - 12:20',
    day: 'Wednesday',
    groups: ['CS-2A', 'CS-2B'],
    duration: '80 min',
    week: 'denominator',
    teachingGroup: 'DS228'
  },
  {
    id: 7,
    subject: 'Operating Systems',
    lecturer: 'Prof. Sarah Johnson',
    classroom: '19312',
    time: '14:20 - 15:40',
    day: 'Wednesday',
    groups: ['CS-3A'],
    duration: '80 min',
    week: 'numerator',
    teachingGroup: 'OS315'
  },
  {
    id: 8,
    subject: 'Network Security',
    lecturer: 'Prof. Michael Chen',
    classroom: '4206',
    time: '09:30 - 10:50',
    day: 'Thursday',
    groups: ['CS-4A'],
    duration: '80 min',
    week: 'both',
    teachingGroup: 'NS419'
  },
  {
    id: 9,
    subject: 'Artificial Intelligence',
    lecturer: 'Prof. Emily Watson',
    classroom: '11508',
    time: '11:00 - 12:20',
    day: 'Thursday',
    groups: ['CS-4A', 'CS-4B'],
    duration: '80 min',
    week: 'denominator',
    teachingGroup: 'AI502'
  },
  {
    id: 10,
    subject: 'Mobile App Development',
    lecturer: 'Prof. James Martinez',
    classroom: '6409',
    time: '09:30 - 10:50',
    day: 'Friday',
    groups: ['CS-3A'],
    duration: '80 min',
    week: 'numerator',
    teachingGroup: 'MA334'
  },
  {
    id: 11,
    subject: 'Advanced Algorithms',
    lecturer: 'Prof. Michael Chen',
    classroom: '21104',
    time: '14:20 - 15:40',
    day: 'Monday',
    groups: ['CS-1A'],
    duration: '80 min',
    week: 'denominator',
    teachingGroup: 'AA156'
  },
  {
    id: 12,
    subject: 'Cloud Computing',
    lecturer: 'Prof. Emily Watson',
    classroom: '10302',
    time: '15:50 - 17:10',
    day: 'Monday',
    groups: ['CS-2A', 'CS-2B'],
    duration: '80 min',
    week: 'numerator',
    teachingGroup: 'CC298'
  },
  {
    id: 13,
    subject: 'Cybersecurity Fundamentals',
    lecturer: 'Prof. Robert Lee',
    classroom: '9215',
    time: '15:50 - 17:10',
    day: 'Tuesday',
    groups: ['CS-1A', 'CS-1B'],
    duration: '80 min',
    week: 'both',
    teachingGroup: 'CY124'
  },
  {
    id: 14,
    subject: 'Machine Learning',
    lecturer: 'Prof. Linda Brown',
    classroom: '14308',
    time: '15:50 - 17:10',
    day: 'Wednesday',
    groups: ['CS-4A'],
    duration: '80 min',
    week: 'numerator',
    teachingGroup: 'ML503'
  },
  {
    id: 15,
    subject: 'Blockchain Technology',
    lecturer: 'Prof. James Martinez',
    classroom: '18409',
    time: '14:20 - 15:40',
    day: 'Thursday',
    groups: ['CS-3A', 'CS-3B'],
    duration: '80 min',
    week: 'both',
    teachingGroup: 'BT387'
  }
];
